version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:post667@db:5432/fastapi
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  celery:
    build: .
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
  

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - default

  celery-beat:
    build: .
    command: celery -A celery_app.celery_app beat --loglevel=info
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/src




volumes:
  postgres_data:
